# Project Metadata
sonar.projectKey=sonar-learning-poc
sonar.projectName=sonar-learning-poc

# Scan ONLY files inside the service package
sonar.inclusions=**/service/**/*.java

# Coverage ONLY for files inside the service package
sonar.coverage.inclusions=**/service/**/*.java

# Explicitly exclude everything else from coverage (DTOs, Configs, Apps, etc.)
sonar.coverage.exclusions=**/model/**,**/dto/**,**/config/**,**/*Application.java,**/*Controller.java,**/*Repository.java