name: "Java MS CI with Gradle"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version : '21'
          distribution: 'temurin'
          cache: 'gradle' # Automatically caches Gradle dependencies to speed up future builds
     # Step 3: Grant execute permission for the Gradle wrapper script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    # Step 4: Run the Gradle build task (compiles code and runs tests)
      - name: Build with Gradle
        run: ./gradlew build